"""Add title field to DocumentModel

Revision ID: a02f4ed637ee
Revises: feb33417c4e5
Create Date: 2025-10-08 03:35:40.676846+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02f4ed637ee'
down_revision = 'feb33417c4e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
