"""Regenerate title field migration

Revision ID: feb33417c4e5
Revises: 5fdedff3b428
Create Date: 2025-10-08 03:34:46.410462+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb33417c4e5'
down_revision = '5fdedff3b428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
