"""Add title field to DocumentModel

Revision ID: 5fdedff3b428
Revises: d81956692a85
Create Date: 2025-10-08 03:31:32.453332+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdedff3b428'
down_revision = 'd81956692a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
